### ISSUE TITLE
Game freeze with True Shot

### ISSUE THREAD

**Issue by XxDragonFang** [Maciej916/Ma-Enchants#11]
**Describe the bug**
When too many arrows fired with this enchant are aimed towards empty space, like the sky or in the end, the client eventually stops "ticking" and freezes. You can still move around, but it appears that entity processing entirely stops. 

**To Reproduce**
Fire a bunch of arrows(>20) with True Shot towards the sky or in a direction that won't collide with anything to allow the arrow to reach entity processing range. Give it a few minutes.

**Expected behavior**
For the arrows to despawn at render range,  and to not destroy the internal server.

**Versions**
- **Ma Enchants**: V2.0.0
- **Forge**: 30.0.42
**Additional context**
I don't know if this helps, but the only thing I was able to spot was that the Rx value for the internal server dropped to 0. I read this value from the f3 screen.

**Comment by IzzelAliz** [comment]
Reproducible with Ma-Enchants-1.15.2-3.1.0, please fix this.

This actually crashed my server several times:

https://paste.ubuntu.com/p/nfRSQH2pqk/

https://paste.ubuntu.com/p/PGff9PcqSf/

**Comment by BasDerilov** [comment]
This issue is still causing crashes big time, please fix this. Same bug:
/issues/38

**Comment by NemecRaphael** [comment]
Is there a planned fix for it? It still happens. Needs to remove arrow entity before it enters render distance

**Comment by Maciej916** [comment]
This should be fixed in [1.19.2-6.0.0](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/4076197)
