### ISSUE TITLE
Floating Enchant

### ISSUE THREAD

**Issue by R088NET** [Maciej916/Ma-Enchants#13]
**Describe the bug**
If an arrow is reflected of the Ender Dragon and hits the play, they will not be able to walk.  They will only be able to move while jumping.  This effect will only go away if you die or kill yourself.

**To Reproduce**
1. Enchant bow with Floating enchant.
2. Head to the end and start fighting the dragon
3. While he is in his perched phase ( in the middle on the ground) show an arrow while close.
4. If they arrow hits you, your screen will zoom in and you will no longer be able to move until death.

**Expected behavior**
Character will no longer be able to move until death.

**Versions**
- Ma-Enchants-1.15.2-3.0.0
- **Forge**:1.15.2 - 31.1.17

**Comment by Maciej916** [comment]
Should be fixed in [v3.3.0](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/3038348)
