### ISSUE TITLE
Faster Attacker enchant doesn't work

### ISSUE THREAD

**Issue by StevenDoesStuffs** [Maciej916/Ma-Enchants#14]
I'm current on the latest version (1.14) atm5, which has Ma Enchants v3.0.0, and the issue is, while the faster attacker enchant makes it seem like the attack speed is faster, the damage is not in fact changed.

**Comment by NighthowlerStudios** [comment]
can be reproduced on all versions, including 1.16.5

**Comment by Maciej916** [comment]
This should be fixed in [1.19.2-6.0.0](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/4076197)
