### ISSUE TITLE
Lumberjack doesn't work

### ISSUE THREAD

**Issue by Yancha3112** [Maciej916/Ma-Enchants#15]
My server is on **1.15.2**, and the mod's version is _"Ma-Enchants-1.15.2-3.1.0"_. I know that this enchant might not work on big trees, but for me it doesn't work at all, even on simple trees. I have other mod installed, but the axe i used was a vanilla iron axe. I tested in singleplayer and it didn't work either. The other enchants are working perfectly.

**Comment by Maciej916** [comment]
You need to press key while mining tree to activate lumberjack. Check Excavate keybind in options by default it's "**c**"
