### ISSUE TITLE
Console INFO error

### ISSUE THREAD

**Issue by MiguelWaffles** [Maciej916/Ma-Enchants#16]
sometimes the items enchanted with this mod disappear from the players inventory,
In addition to that, I get this error in the console.

[INFO] .... [STDOUT/]: [com.maciej916.maenchants.ForgeEventSubscriber:onPlayerClone:50]: com.maciej916.maenchants.capabilities.Enchants@7b494a97

**Comment by Maciej916** [comment]
This should be fixed in 1.16 v3.2.1 but im not 100% sure.
