### ISSUE TITLE
[1.16.1] Crash whilst playing on a server.

### ISSUE THREAD

**Issue by Gbergz** [Maciej916/Ma-Enchants#18]
Currently running on my modpack Limitless 3 w/ Ma Enchants, and server crashed.

**Crash-Report:** https://hastebin.com/etupoqobaq.pl

**Minecraft:** 1.16.1
**Forge:** 32.0.106
**Ma-Enchants:** 3.2.1

Any ideas?
**-** Gbergz

**Comment by Maciej916** [comment]
Fixed in [v3.3.0](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/3038348)
