### ISSUE TITLE
Some of "my" ideas. 

### ISSUE THREAD

**Issue by slowiu06** [Maciej916/Ma-Enchants#2]
**Bow and/or Crossbow:**

_Arrow Splash_ - creates a splash potion effect from arrows enchanted with potion effects. Can be used only with fully charged bow. Creates an effect even after hitting the ground. (Cannot be combined with Quick Draw, Triple Shot, Arrow Splash and Crossbow's: Quick Shot);

_Barrage_ (I-III) - rapidly shots additionas 1-3 arrows. Can be used only with fully charged bow. Between each arrow we should have a few ticks to change a bit direction of next arrow. Level incrases number of aditional arrows. (Cannot be combined with Quick Draw, Chain, Arrow Splash and Crossbow's: Multishot, Quick Shot). Idea came from https://pathofexile.gamepedia.com/Barrage ;

_Chain_ (I-III) - after arrow hit a target it looks in close range for another target. Can be used only with fully charged bow. Level inrecase the range and number of targets. (Cannot be combined with Quick Draw, Triple Shot, Arrow Splash and Crossbow's: Quick Shot, Multishot, Piercing). Idea came from https://pathofexile.gamepedia.com/Chain_Support ;

_Enderman's Agony_ - allows to hit endermans and the like.

PS. _Floating_ and _Paralysis_ should not be combinable with each other.

**Axe:**

_Tomahawk_ (I-III) - let us throw an Axe. After throw the Axe should be unusable for a while. Something like Loyality + Channeling for Trident, but Axe stays in it's place on hotbar to reduce the mess. Levels reduce the cooldown. There was a mod named like this with similar functionality.

**Sword:**

_Beheading_ (I-III) - increase a chance of dropping a head. Can be applied to an Axe;

Headhunter (I-III) - each hit have a chance to steal positive potion effect from enemy. Idea came from https://pathofexile.gamepedia.com/Headhunter .

**Boots:**

_Traveller's Blessing_ (I-III) - Increases movespeed but without using potion effect, so potions will be still worth something. Higher lvl = higher speed boost.

**Trident:**

_Storm_ (I-II-III) - at lvl I Channeling is able to hit with a lightning even without thunderstorm. At lvl II it summons a lightning even without hitting an entity. At lvl III there is more lightnings (like aoe skill, can be used only with fully charged Trident);

_Lightning Coil_ (I-III) - Trident summons a lightning on hitted block every few seconds for a duration or before we pick it up. Level incrases duration and reduces time between each lightning. (cannot be combined with Storm, Loyality, Channeling, Riptide, can be used only with fully charged Trident).

PS. Tridents should be protected from being damaged by lightning.

**Any:**

_Endereturn_ - something like good-known Soulbound enchantment but after death It moves items to player's Enderchest. If there is no space items are dropped in place of death.

**Fishing rod:**

_Escape Line_ - hitting a block exactly above teleports us on a surface. Don't work in Nether. (cannot be combined with Grappling);

_Grappling_ - Rod attracts us to the block it has hit. (cannot be combined with Escape line);

_Treasure Hunter_ - you are not getting any fishes but doubles a chance for other items.

**Pickaxe:**

_AIO_ - Mines wood and dirt with the same speed as cobblestone.

**Comment by slowiu06** [comment]
Cześć, czy żaden z pomysłów nie przypadł Ci do gustu?

**Comment by Maciej916** [comment]
> Cześć, czy żaden z pomysłów nie przypadł Ci do gustu?
I like your ideas but implement them will take a lot of time with i don't have currently.
