### ISSUE TITLE
[1.16.5] Books set to false in config still show up in game

### ISSUE THREAD

**Issue by jengendler** [Maciej916/Ma-Enchants#26]
Minecraft: 1.16.5 (and 1.16.4)
Mod: v3.5.0

In the `ma-enchants-common.toml` file, setting an enchant to `false ` does not disable the book in-game. The book still shows up in Library villager trade lists and in the enchanting table.

**Comment by DerekM07** [comment]
Can confirm this is true for me also. 1.16.5/3.5.0

**Comment by Maciej916** [comment]
They are still will be visible but not obtainable in enchant
