### ISSUE TITLE
Step Assist breaks stairs after equipping it.

### ISSUE THREAD

**Issue by CupOJo1** [Maciej916/Ma-Enchants#27]
Stairs work normally but when you equip an item with the step assist enchantment, it breaks stairs. With the enchantment, stairs work fine but when I take it off, it acts like a full block.

**Comment by Maciej916** [comment]
This should be fixed in [1.19.2-6.0.0](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/4076197)
