### ISSUE TITLE
[1.14.4] Crash when i died.

### ISSUE THREAD

**Issue by Gbergz** [Maciej916/Ma-Enchants#3]
**Describe the bug**
I played on a world for a little bit then i died & crashed.

**To Reproduce**
1. Play on a world
2. Die, to anything.
3. Crash

**Expected behavior**
Not crashing, obviously. :)

**Versions**
- **Ma Enchants**: 1.5.1
- **Forge**: 28.1.90

**Additional context**
Crash report: [https://gist.github.com/Gbergz/f97b6a2d776910f58f77972f8fcdd3cc](https://gist.github.com/Gbergz/f97b6a2d776910f58f77972f8fcdd3cc)

**Comment by Maciej916** [comment]
Thank you for reporting. I'll fix this in next update.

**Comment by Maciej916** [comment]
Fixed in [v1.5.2](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/2832034)
