### ISSUE TITLE
soft fall enchant causes server to become very buggy when taking fall dmg and player to be unable to move with infinite waiting for server 

### ISSUE THREAD

**Issue by Jordan231111** [Maciej916/Ma-Enchants#30]
01.06 17:57:36 [Server] Server thread/ERROR [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
01.06 17:57:36 [Server] INFO Index: 1
01.06 17:57:36 [Server] INFO Listeners:
01.06 17:57:36 [Server] INFO 0: NORMAL
01.06 17:57:36 [Server] INFO 1: ASM: class com.maciej916.maenchants.common.subscribers.ForgeEventSubscriber onFall(Lnet/minecraftforge/event/entity/living/LivingFallEvent;)V
01.06 17:57:36 [Server] INFO 2: ASM: class com.wonderfulenchantments.enchantments.PhoenixDiveEnchantment onFall(Lnet/minecraftforge/event/entity/living/LivingFallEvent;)V
01.06 17:57:36 [Server] INFO 3: ASM: atomicstryker.infernalmobs.common.EntityEventHandler@5352c8e1 onEntityLivingFall(Lnet/minecraftforge/event/entity/living/LivingFallEvent;)V
01.06 17:57:36 [Server] INFO 4: ASM: class com.thevortex.allthemodium.events.ArmorEvents onPlayerFall(Lnet/minecraftforge/event/entity/living/LivingFallEvent;)V
01.06 17:57:36 [Server] INFO 5: ASM: class net.silentchaos512.gear.event.GearEvents onLivingFall(Lnet/minecraftforge/event/entity/living/LivingFallEvent;)V
01.06 17:57:36 [Server] INFO 6: net.minecraftforge.eventbus.EventBus$$Lambda$2728/1548428044@2d5cb3ae
01.06 17:57:36 [Server] INFO 7: ASM: com.blakebr0.mysticalagriculture.handler.AugmentHandler@1ce3f170 onLivingFall(Lnet/minecraftforge/event/entity/living/LivingFallEvent;)V
01.06 17:57:36 [Server] INFO 8: ASM: com.github.alexthe666.iceandfire.event.ServerEvents@339d65aa onEntityFall(Lnet/minecraftforge/event/entity/living/LivingFallEvent;)V
01.06 17:57:36 [Server] INFO java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
01.06 17:57:36 [Server] INFO at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
01.06 17:57:36 [Server] INFO at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
01.06 17:57:36 [Server] INFO at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
01.06 17:57:36 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
01.06 17:57:36 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
01.06 17:57:36 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
01.06 17:57:36 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
01.06 17:57:36 [Server] INFO at net.minecraftforge.fml.network.simple.SimpleChannel.sendToServer(SimpleChannel.java:104)
01.06 17:57:36 [Server] INFO at com.maciej916.maenchants.common.handler.HandlerSoftFall.handlerFall(HandlerSoftFall.java:28)
01.06 17:57:36 [Server] INFO at com.maciej916.maenchants.common.subscribers.ForgeEventSubscriber.onFall(ForgeEventSubscriber.java:62)
01.06 17:57:36 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_28_ForgeEventSubscriber_onFall_LivingFallEvent.invoke(.dynamic)
01.06 17:57:36 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
01.06 17:57:36 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
01.06 17:57:36 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
01.06 17:57:36 [Server] INFO at net.minecraftforge.common.ForgeHooks.onLivingFall(ForgeHooks.java:385)
01.06 17:57:36 [Server] INFO at net.minecraft.entity.LivingEntity.func_225503_b_(LivingEntity.java:1373)
01.06 17:57:36 [Server] INFO at net.minecraft.entity.player.PlayerEntity.func_225503_b_(PlayerEntity.java:1472)
01.06 17:57:36 [Server] INFO at net.minecraft.block.Block.func_180658_a(Block.java:332)
01.06 17:57:36 [Server] INFO at net.minecraft.entity.Entity.func_184231_a(Entity.java:914)
01.06 17:57:36 [Server] INFO at net.minecraft.entity.LivingEntity.func_184231_a(LivingEntity.java:273)
01.06 17:57:36 [Server] INFO at net.minecraft.entity.player.ServerPlayerEntity.func_71122_b(ServerPlayerEntity.java:868)
01.06 17:57:36 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_147347_a(ServerPlayNetHandler.java:846)
01.06 17:57:36 [Server] INFO at net.minecraft.network.play.client.CPlayerPacket.func_148833_a(SourceFile:122)
01.06 17:57:36 [Server] INFO at net.minecraft.network.play.client.CPlayerPacket$PositionPacket.func_148833_a(SourceFile:56)
01.06 17:57:36 [Server] INFO at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21)
01.06 17:57:36 [Server] INFO at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
01.06 17:57:36 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
01.06 17:57:36 [Server] INFO at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
01.06 17:57:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734)
01.06 17:57:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
01.06 17:57:36 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
01.06 17:57:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717)
01.06 17:57:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711)
01.06 17:57:36 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103)
01.06 17:57:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696)
01.06 17:57:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646)
01.06 17:57:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
01.06 17:57:37 [Multicraft] Skipped 4 lines due to rate limit (150/s)
01.06 17:57:37 [Server] INFO at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[idk.jar:36.1] {}
01.06 17:57:37 [Server] INFO at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
01.06 17:57:37 [Server] INFO at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
01.06 17:57:37 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
01.06 17:57:37 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
01.06 17:57:37 [Server] INFO at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
01.06 17:57:37 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292] {}
01.06 17:57:37 [Server] INFO at net.minecraftforge.fml.network.simple.SimpleChannel.sendToServer(SimpleChannel.java:104) ~[forge:?] {re:classloading}
01.06 17:57:37 [Server] INFO at com.maciej916.maenchants.common.handler.HandlerSoftFall.handlerFall(HandlerSoftFall.java:28) ~[ma-enchants:1.16.5-3.6.0] {re:classloading}
01.06 17:57:37 [Server] INFO at com.maciej916.maenchants.common.subscribers.ForgeEventSubscriber.onFall(ForgeEventSubscriber.java:62) ~[ma-enchants:1.16.5-3.6.0] {re:classloading}
01.06 17:57:37 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_28_ForgeEventSubscriber_onFall_LivingFallEvent.invoke(.dynamic) ~[?:?] {}
01.06 17:57:37 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
01.06 17:57:37 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
01.06 17:57:37 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
01.06 17:57:37 [Server] INFO at net.minecraftforge.common.ForgeHooks.onLivingFall(ForgeHooks.java:385) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:dungeons_plus.mixins.json:ForgeHooksMixin,pl:mixin:A}
01.06 17:57:37 [Server] INFO at net.minecraft.entity.LivingEntity.func_225503_b_(LivingEntity.java:1373) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:placebo:placeboshieldblock,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 17:57:37 [Server] INFO at net.minecraft.entity.player.PlayerEntity.func_225503_b_(PlayerEntity.java:1472) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,xf:fml:xaerominimap:xaero_playerentity_iswearing,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,xf:fml:xaerominimap:xaero_playerentity_iswearing,pl:mixin:APP:balancedenchanting.mixins.json:PlayerEntityMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 17:57:37 [Server] INFO at net.minecraft.block.Block.func_180658_a(Block.java:332) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dankstorage.mixins.json:MixinBlock,pl:mixin:APP:randomenchants.mixins.json:BlockMixin,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 17:57:37 [Server] INFO at net.minecraft.entity.Entity.func_184231_a(Entity.java:914) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:add_custom_entity_collision,pl:mixin:APP:randompatches.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 17:57:37 [Server] INFO at net.minecraft.entity.LivingEntity.func_184231_a(LivingEntity.java:273) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:set_player_field,xf:fml:placebo:placeboshieldblock,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:astralsorcery:water_movement_slowdown_prevention,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 17:57:37 [Server] INFO at net.minecraft.entity.player.ServerPlayerEntity.func_71122_b(ServerPlayerEntity.java:868) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
01.06 17:57:37 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_147347_a(ServerPlayNetHandler.java:846) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,pl:mixin:A}
01.06 17:57:37 [Server] INFO at net.minecraft.network.play.client.CPlayerPacket.func_148833_a(SourceFile:122) ~[?:?] {re:classloading}
01.06 17:57:37 [Server] INFO at net.minecraft.network.play.client.CPlayerPacket$PositionPacket.func_148833_a(SourceFile:56) ~[?:?] {re:classloading}
01.06 17:57:37 [Server] INFO at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
01.06 17:57:37 [Server] INFO at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
01.06 17:57:37 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
01.06 17:57:37 [Server] INFO at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
01.06 17:57:37 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 17:57:37 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 17:57:37 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
01.06 17:57:37 [Server] INFO at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 17:57:37 [Server] INFO at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 17:57:38 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
01.06 17:57:38 [Server] INFO at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 17:57:41 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 17:57:42 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:resourcefulbees.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
01.06 17:57:42 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292] {}

**Comment by Gbergz** [comment]
Can confirm that my servers logs are being spammed by this message sent above.

**Part of logs:** https://gist.github.com/Gbergz/08fa604efd014f91cac0bc3f93621d38

**Minecraft:** 1.16.5
**Forge:** 36.1.31
**MA Enchants**: [Ma-Enchants-1.16.5-3.6.0](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/3281741)

**Comment by Maciej916** [comment]
Fixed in [v3.6.1](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/3419064)
