### ISSUE TITLE
Game crashes when use true shot on 1.16.5

### ISSUE THREAD

**Issue by KrystalTheFox** [Maciej916/Ma-Enchants#36]
Hello. for the past couple of months, when I use true shot sometimes the game crashes and Idk whats causing it.

Here is the crash report. The crash report also has a blame report in it too.
Minecraft version is 1.16.5

https://pastebin.pl/view/0424b884

**Comment by KrystalTheFox** [comment]
Im guessing this is a well known issue?

**Comment by Maciej916** [comment]
This should be fixed in [1.19.2-6.0.0](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/4076197)
