### ISSUE TITLE
{1.18.1} game crashed after putting on boots with Blazing walker II

### ISSUE THREAD

**Issue by thisheresir** [Maciej916/Ma-Enchants#37]
game was fine till I put them on
[crash-2022-02-08_20.13.02-server.txt](https://github.com/Maciej916/Ma-Enchants/files/8028613/crash-2022-02-08_20.13.02-server.txt)

if you need any more info just tell me

**Comment by Vegifoo** [comment]
Also having issues with this enchantment, error disconnects me from the server and I need to delete my player data in order to log back in.

**Comment by Maciej916** [comment]
This should be fixed in [1.19.2-6.0.0](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/4076197)
