### ISSUE TITLE
floating arrow causes crash (multiplayer dedicated server)

### ISSUE THREAD

**Issue by Wedge1453** [Maciej916/Ma-Enchants#38]
here's the crash log: https://pastebin.com/PW8ZW72t

**Comment by BasDerilov** [comment]
Please fix this, same issue has been present for a while
/issues/11

**Comment by BasDerilov** [comment]
More cases of this bug 
/issues/36
/issues/34

**Comment by Maciej916** [comment]
This should be fixed in [1.19.2-6.0.0](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/4076197)
