### ISSUE TITLE
Can't join server when wearing Blaze Walker enchantment

### ISSUE THREAD

**Issue by Jayerd** [Maciej916/Ma-Enchants#40]
![image](https://user-images.githubusercontent.com/98251669/158722515-dc4a603a-1acd-4c93-933a-7776580bccfe.png)

https://mclo.gs/LVVO48z

**Comment by Maciej916** [comment]
This should be fixed in [1.19.2-6.0.0](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/4076197)

**Comment by SAGESSE-CN** [comment]
same issue for 1.18.2

https://mclo.gs/fbFwtlH
