### ISSUE TITLE
Inconsistency in Mod ID across versions causes compatibility issues

### ISSUE THREAD

**Issue by Dariensg** [Maciej916/Ma-Enchants#44]
Ma Enchants for 1.16 has the Mod ID "ma-enchants," while 1.17 and 1.18 have the Mod ID "maenchants." This can cause issues with compatibility with other mods that rely on the Mod ID to determine compat features. One such example is the mod Neko's Enchanted Books, which relies on Mod IDs to assign custom book textures to enchantment books. Mod IDs should typically never be changed if at all possible for reasons such as this, and in cases where they must be changed, the change should be reflected across all versions. It would be great if you could please update the Mod ID of one type or the other so that there is consistency, thank you!

**Comment by Maciej916** [comment]
Modid will not longer change since 1.18
