### ISSUE TITLE
When using a trident and using riptide, falling to your death results in a game crash.

### ISSUE THREAD

**Issue by She-leap** [Maciej916/Ma-Enchants#5]
**Describe the bug**
When using a trident and using riptide (not underwater in rain), falling to your death results in a game crash.

**To Reproduce**
1. Get a trident with Riptide III and maybe another enchantment 
2. Just fly around
3. Die

**Expected behavior**
Just being able to respawn without game crash

**Versions**
- **Ma Enchants**: 1.5.1
- **Forge**: 28.1.92

**Additional context**

[crash-2019-11-24_10.06.38-client.txt](https://github.com/Maciej916/Ma-Enchants/files/3883720/crash-2019-11-24_10.06.38-client.txt)
[latest.log](https://github.com/Maciej916/Ma-Enchants/files/3883721/latest.log)
[debug.log](https://github.com/Maciej916/Ma-Enchants/files/3883722/debug.log)

**Comment by Maciej916** [comment]
Thank you for reporting. I'll fix this in next update.

**Comment by Maciej916** [comment]
Fixed in [v1.5.2](https://www.curseforge.com/minecraft/mc-mods/ma-enchants/files/2832034)
