### ISSUE TITLE
customizability 

### ISSUE THREAD

**Issue by ThsHaunted124** [Maciej916/Ma-Enchants#7]
Could you add a way to disable and enable certain enchants in a config? And also a limit cap for the amount of levels an enchantment can have? 

This way people can customize the enchantments they find too strong or too weak

**Comment by Maciej916** [comment]
You can currently disable enchants in config `<world>/serverconfig/ma-enchants-server.cfg`
About customize is not currently possible but if you have any suggestions how to balance enchantments you can give your opinion.
